import type { Metadata } from 'next';
import './globals.scss';

import '@/styles/main.scss';
import { Header } from '@/components/header';
import { Footer } from '@/components/footer';
import { Menu } from '@/sanity/sanity-types';
import { getMenu } from '@/sanity/sanity.query';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const options = { next: { revalidate: 30 } };

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menu: Menu[] = await getMenu(options);
  return (
    <html lang='en'>
      <body>
        <Header menu={menu[0]} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
